### ISSUE TITLE
issue with downloading models

### ISSUE THREAD

**Issue by alighofrani95** [AtaaEddin/beautiful-sign-language-tr#3]
Hi Dear Ataa,

I'm so interested in this project. and try to re-implement thisb ut I faced with downloading the models.

the storage.googleapis.com doesn't response to download the models.it returns the below error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error><Code>UserProjectAccountProblem</Code><Message>User project billing account not in good standing.</Message><Details>The billing account for the owning project is disabled in state closed</Details></Error>

Could you please upload the the rgb and oflow models to some other places?

**Comment by AtaaEddin** [comment]
Hi Ali, Thank you for showing your interest in this project and for raising this issue!!
I Updated the links, now you should be able to download and run the project without any trouble.
But please consider reading the Readme.md file again as i also updated the requirements as i made some notes too about an error occurs when building this project with newer python versions. So you have to use older versions like python3.6.

Happy coding!!

**Comment by alighofrani95** [comment]
> Hi Ali, Thank you for showing your interest in this project and for raising this issue!!
> I Updated the links, now you should be able to download and run the project without any trouble.
> But please consider reading the Readme.md file again as i also updated the requirements as i made some notes too about an error occurs when building this project with newer python versions. So you have to use older versions like python3.6.
> 
> Happy coding!!

thanks a lot, problem solved ...
